### ISSUE TITLE
Fails to build with Boost 1.70.0

### ISSUE THREAD

**Issue by jbeich** [sabelnikov/epee#1]
Regressed by boostorg/asio@a72fbb0b867f:
```c++
In file included from demo/demo_levin_server/demo_levin_server.cpp:30:
In file included from demo/demo_levin_server/demo_levin_server.h:33:
In file included from demo/../include/net/levin_server_cp2.h:32:
In file included from demo/../include/net/abstract_tcp_server2.h:275:
demo/../include/net/abstract_tcp_server2.inl:170:20: error: no member named 'get_io_service' in
      'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
    return socket_.get_io_service();
           ~~~~~~~ ^
demo/../include/net/abstract_tcp_server2.inl:274:28: error: no member named 'get_io_service' in
      'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
      size_t cnt = socket_.get_io_service().run_one();
                   ~~~~~~~ ^
demo/../include/net/abstract_tcp_server2.inl:284:28: error: no member named 'get_io_service' in
      'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
      size_t cnt = socket_.get_io_service().poll_one();
                   ~~~~~~~ ^
```

**Comment by sabelnikov** [comment]
Hi! Thank you for reportin a problem, actually this version of library is not the last one, we actively use it in this project https://github.com/hyle-team/zano 
But i'll update this repo with the last one in few hours, hope this will help to solve this.

**Comment by cryptozoidberg** [comment]
fyi: I moved repo to our team account, just in case your git links are broken.

**Comment by cryptozoidberg** [comment]
Try with f5e182c, this is the latest version

**Comment by jbeich** [comment]
Still fails:
```c++
In file included from demo_http_server/demo_http_server.cpp:29:
In file included from demo_http_server/demo_http_server.h:33:
In file included from ../include/net/http_server_cp2.h:33:
In file included from ../include/net/abstract_tcp_server2.h:288:
../include/net/abstract_tcp_server2.inl:173:20: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
    return socket_.get_io_service();
           ~~~~~~~ ^
../include/net/abstract_tcp_server2.inl:277:28: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
      size_t cnt = socket_.get_io_service().run_one();
                   ~~~~~~~ ^
../include/net/abstract_tcp_server2.inl:287:28: error: no member named 'get_io_service' in 'boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>'
      size_t cnt = socket_.get_io_service().poll_one();
                   ~~~~~~~ ^
3 errors generated.
```
